export const GET_ERRORS = "GET_ERRORS";
export const GET_TODO = "GET_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const CREATE_TODO = "CREATE_TODO";
export const ENABLE_LOADING = "ENABLE_LOADING";
export const DISABLE_LOADING = "DISABLE_LOADING";
export const DELETE_BUCKET = "DELETE_BUCKET";
export const SET_CURRENT_BUCKET = "SET_CURRENT_BUCKET";